Make it fail

diff --git a/.github/workflows/style-and-sp-check.yml b/.github/workflows/style-and-sp-check.yml
--- a/.github/workflows/style-and-sp-check.yml
+++ b/.github/workflows/style-and-sp-check.yml
@@ -34,9 +34,12 @@ jobs:
           results=$(Rscript "components/spell-check.R")
           echo "::set-env name=spell_check_results::$results"
 
+      # If there are too many spell checks, this will stop everything
       - name: Check on spell check results
-        # if: spell_check_results > 3
-        run: echo $spell_check_results
+        if:  $spell_check_results > 3
+        run: |
+        echo 'Too many spelling errors; $spell_check_results'
+        exit 1
 
       - name: Run styler
         run: Rscript -e "styler::style_file(list.files(pattern = 'Rmd$', recursive = TRUE, full.names = TRUE));warnings()"
