I might need some tabs?

diff --git a/.github/workflows/style-and-sp-check.yml b/.github/workflows/style-and-sp-check.yml
--- a/.github/workflows/style-and-sp-check.yml
+++ b/.github/workflows/style-and-sp-check.yml
@@ -38,8 +38,8 @@ jobs:
       - name: Check on spell check results
         if:  $spell_check_results > 3
         run: |
-        echo 'Too many spelling errors; $spell_check_results'
-        exit 1
+          echo "Too many spelling errors; $spell_check_results"
+          exit 1
 
       - name: Run styler
         run: Rscript -e "styler::style_file(list.files(pattern = 'Rmd$', recursive = TRUE, full.names = TRUE));warnings()"
